### PR TITLE
Added Bouachain Mainnet

### PR DESCRIPTION
**Pull request by Bouachain**

### CODE REVIEW

**Review by liangping — CHANGES_REQUESTED** [review]
How many validators do you have?

**Comment by Bouachain** [comment]
1 ATM, will increase in a long run.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by liangping** [comment]
We only accept blockchains which have 10+ validators on mainnet

**Comment by Bouachain** [comment]
Ok that's alright, once we have up to 10 validators. We will send a notification.

**Pull request closed without merging**
